site_name: LatentQuant
site_description: Пакет для работы с эмбеддингами и их сжатием
site_author: Master-Star-Field

# Ключевое изменение - указываем другую папку для исходников
docs_dir: mkdocs_docs  # Папка с исходными markdown файлами
site_dir: docs         # Папка для собранного сайта (будет использоваться GitHub Pages)

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: purple
    - scheme: slate
      primary: teal
      accent: lime

repo_name: Master-Star-Field/LatentQuant
repo_url: https://github.com/Master-Star-Field/LatentQuant

nav:
  - Главная: api/index.md
  - API Документация:
    - Все модули: api/all.md
    - Модели: api/models.md
    - Логгеры: api/loggers.md
    - Утилиты: api/utils.md
  - Примеры: examples.md
  - Установка: installation.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_category_heading: true
            members_order: source
            heading_level: 2
            merge_init_into_class: true
            show_if_no_docstring: false
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - tables

watch:
  - embeddings_squeeze