# ClearML Credentials Configuration
# Copy this file to clearml_credentials.yaml and fill in your credentials
# The clearml_credentials.yaml file should be gitignored

api_host: "https://api.clear.ml"
web_host: "https://app.clear.ml"
files_host: "https://files.clear.ml"
api_key: "YZHY0DIXHI0QZ5JWBXR0ZBDKV6KM60"
api_secret: "BRqAEdqAR1rIkaOfFo5m_o8q1nAz9oxttZSH7YMsGJgNU8J9FG3M7M-4VOEQr9J-MRQ"